from pathlib import Path
p=Path(__file__).resolve().parents[1]/'scripts/hud.gd'
s=p.read_text(encoding='utf8')
s=s.replace('"凯恩 · 裂影匕首" if game.active_slot==0 else "洛铆 · 机械师"','["凯恩 · 裂影匕首","洛铆 · 机械师","伊瑟 · 矿族游侠"][game.active_slot]')
s=s.replace('game.rooms[game.room].id+"  /  断电之夜"','game.rooms[game.room].id+"  /  v0.4.0"')
s=s.replace('"1 凯恩 %d%%     2 洛铆 %d%%     F 切换"%[roundi(game.party_hp[0]),roundi(game.party_hp[1]/1.1)]','"1 凯恩  2 洛铆"+("  3 伊瑟" if game.flags.get("ranger",false) else "")+"  /  F 切换"')
s=s.replace('"A/D 移动   W/S 攀梯   Space 跳跃   J/K 攻击   Shift 闪避   L 格挡   E 交互   Q 钩索   M 地图   T 技能   Esc 暂停"','"A/D 移动  W/S 攀梯  Alt 冲跑  Space 跳跃  J/K 攻击  Shift 翻滚  L 弹反  E 交互  Q 钩索  Tab 总览  M 地图  T 技能"')
s=s.replace('3.7 if enemy.kind=="boss" else 2.1','3.7 if enemy.boss() else 2.1').replace('"落锤！" if enemy.kind=="boss" else "!"','enemy.pattern+"！"')
s=s.replace('"序章 · 断电之夜     /     v0.1 可玩原型"','"灰闸囚厂 × 锈脊齿轮井   /   18 房间 · v0.4.0"')
s=s.replace('"凯恩 · 匕首" if game.active_slot==0 else "洛铆 · 机械重击"','["凯恩 · 匕首","洛铆 · 机械重击","伊瑟 · 弓箭"][game.active_slot]')
s=s.replace('"技能点 %d  /  每招 1 点。Ctrl + J / K，消耗 18 魔力。"','"技能点 %d / 每招 1 点。Ctrl + J / K 攻击，Ctrl + Space 空中冲刺。"')
s=s.replace('"共鸣变身与其他同伴将在后续章节制作。"','"空中 K 下砸；蓝色墙面抓壁 + Space 蹬墙；低障碍前跳跃翻越。"')
s=s.replace('for i in range(11):','for i in range(game.rooms.size()):').replace('i%4;var row := i/4','i%5;var row := i/5')
s=s.replace('col*w*.19,h*.28+row*125','col*w*.15,h*.27+row*82').replace('Vector2(w*.16,88)','Vector2(w*.14,72)').replace('Vector2(13,60)','Vector2(13,55)').replace('21,TEXT if known else MUTED','17,TEXT if known else MUTED')
s=s.replace('if col<3 and i<10:draw_line(p+Vector2(w*.16,44),p+Vector2(w*.19,44),MUTED,2)','')
s=s.replace('"◇ 休息灯   /   蓝色 ◇ 钩索锚点   /   原路与囚厂回环可以再次探索"','"主线：R01-01 → 08 → R02-01 → 08 → 维修所；矿牢为轴承台支线。"')
s=s.replace('\t\tif game.room==10:\n\t\t\ttext_at(Vector2(w/2-160,200),"水位 %.1f / 2  ·  %s"%[game.water[2],"旁路开放" if game.water[3] else "蒸汽隔离"],18,GOLD)','\t\tvar alive:=0\n\t\tfor enemy in game.enemies:\n\t\t\tif is_instance_valid(enemy) and enemy.hp>0:alive+=1\n\t\ttext_at(Vector2(w-368,153),"本室敌人 %d   /   Tab 查看完整路线"%alive,16,GOLD)')
s=s.replace('for i in range(2):','for i in range(3):').replace('["裂影刺","齿刃旋舞"] if game.active_slot==0 else ["铜核修补击","齿轮过载"]','[["裂影刺","齿刃旋舞","裂影空冲"],["铜核修补击","齿轮过载","机械推进"],["穿甲射击","裂界强弓","游侠空冲"]][game.active_slot]')
s=s.replace('w*.18+i*350,h*.44','w*.12+i*w*.27,h*.44').replace('game.learn_skill.bind(i),320','game.learn_skill.bind(i),w*.25')
s=s.replace('\t\tadd_button("返回",Vector2(w*.18,h*.57),func():game.set_screen("play"))','\t\tfor slot in game.available_slots():add_button(["凯恩","洛铆","伊瑟"][slot],Vector2(w*.18+slot*160,h*.58),game.menu_actor.bind(slot),140)\n\t\tadd_button("返回",Vector2(w*.18,h*.84),func():game.set_screen("play"))')
p.write_text(s,encoding='utf8')
